version: '2'

services:
  redis:
    image: redis:7.2.0-alpine3.18

  web: &web
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    depends_on:
      - redis
    ports:
      - 8080:8080

  test:
    <<: *web
    command: go test ./... -v -cover
